# Generated by Django 5.0.3 on 2024-04-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.date(2024, 4, 1), verbose_name='Дата производства'),
        ),
    ]
